### ISSUE TITLE
安装上 会生成很多缓存

### ISSUE THREAD

**Issue by yuanzhihai** [top-think/think-annotation#2]

**Comment by yunwuxin** [comment]
缓存有什么问题么

**Comment by yuanzhihai** [comment]
默认就是要生成很多缓存吗




------------------ 原始邮件 ------------------
发件人: 云无心 <notifications@github.com>
发送时间: 2019年6月24日 17:13
收件人: top-think/think-annotation <think-annotation@noreply.github.com>
抄送: 听风吹雨 <396751927@qq.com>, Author <author@noreply.github.com>
主题: 回复：[top-think/think-annotation] 安装上 会生成很多缓存 (#2)




缓存有什么问题么
