### ISSUE TITLE
请修复一下循环依赖的问题呀

### ISSUE THREAD

**Issue by bain2018** [top-think/think-annotation#22]
以下是我的修复方法，请参考

` ``

protected function autoInject()
    {
        if ($this->app->config->get('annotation.inject.enable', true)) {
            $this->app->resolving(function ($object, $app) {
                $class=get_class($object);
                if ($this->isInjectClass($class)) {

                    if (!$app->has($class))
                    {
                        $app->bind($class,$object);
                    }

                    $refObject = new ReflectionObject($object);
                    foreach ($refObject->getProperties() as $refProperty) {
                        if ($refProperty->isDefault() && !$refProperty->isStatic()) {
                            $attrs = $refProperty->getAttributes(Inject::class);
                            if (!empty($attrs)) {
                                if (!empty($attrs[0]->getArguments()[0])) {
                                    $type = $attrs[0]->getArguments()[0];
                                } elseif ($refProperty->getType() && !$refProperty->getType()->isBuiltin()) {
                                    $type = $refProperty->getType()->getName();
                                }

                                if (isset($type)) {

                                    if ($app->has($type))
                                    {
                                        $value=$app->get($type);
                                    }else{
                                        $value = $app->make($type);
                                    }

                                    if (!$refProperty->isPublic()) {
                                        $refProperty->setAccessible(true);
                                    }
                                    $refProperty->setValue($object, $value);
                                }
                            }
                        }
                    }
                    if ($refObject->hasMethod('__injected')) {
                        $app->invokeMethod([$object, '__injected']);
                    }
                }
            });
        }
    }

```

**Comment by yunwuxin** [comment]
依赖注入本来就不支持循环依赖
