### ISSUE TITLE
多应用多目录报错

### ISSUE THREAD

**Issue by herowind** [top-think/think-annotation#28]
我的目录是 app/ma/controller/sub
类是 Test 
提示错误  找不到  sub/Test
找到原因是 trait InteractsWithRoute  91行
$prefix   = str_replace($this->controllerSuffix . '.php', '', str_replace('/', '.', $filename));
改成
$prefix   = str_replace($this->controllerSuffix . '.php', '', str_replace('\\\\', '.', $filename));
就好用啦。

**Comment by herowind** [comment]
$prefix = str_replace($this->controllerSuffix . '.php', '', str_replace('\\', '.', $filename));

**Comment by yunwuxin** [comment]
不支持多应用
