### ISSUE TITLE
希望能兼容apidoc的注解语法

### ISSUE THREAD

**Issue by lg970044** [top-think/think-annotation#5]
apidoc这块的注解语法是最简洁的，生态也是很完善，如果能够兼容apidoc中的接口注解语法，有使用apidoc的情况下就不需要再多写路由的配置注解。

@api {get} /user/:id Request User information

**Comment by LazyHuman** [comment]
您好
您说的需求和理由，我已经充分的了解到了。

我会在之后进行融合或者留出接口转换规则的，您看这样是否符合您的使用需要求呢？
