### ISSUE TITLE
symfony/class-loader 更新导致类找不到

### ISSUE THREAD

**Issue by congpeijun** [top-think/think-annotation#8]
symfony/class-loader 已经弃用，更新think-annotation最新版，导致项目autoload 失效。

**Comment by sunanzhi** [comment]
是不是 scanDir 这个方法里面调用了symfony 的 ClassMapGenerator::createMap($dir) ，然后这个方法取到的结果是个二维数组，key才是类名，value是路径。我应该跟你遇到了同样的问题。

**Comment by sunanzhi** [comment]
看到有人PR了，但是没有人merge。
